# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 243df45474be6fe633b358fcdbabbf9a40ef2b7db07469867a4060715b651ea25f79485478050cc3d6b8040e919909c09902e0b553c5ec2e870d0589a9bc8708

test:
  secret_key_base: 44f0a9a0ad751a6ed7ea9898c003af0cb198e7e41ae862061c75084d6ba49f4f90fc6ba753cd2ac84ce61263b5abde9c21395522c8240295805c1c9bfd3ccebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
